#pragma once
#include <stdio.h>
#include <stdexcept>
#include <sstream>
#include <filesystem>

#if defined(_WIN32) || defined(_WIN64)
    #include <process.h>
    #define GETPID _getpid
#else
    #include <unistd.h>
    #define GETPID getpid
#endif

namespace JSL::Plotting
{

    enum class Output
    {
        Transient   = 0,    // Live updates, closes with app
        Persistent  = 1,    // Live updates, stays open (multiplot issues)
        Scripted    = 2,    // Generates .gp file
    };


    namespace internal{
        std::string makeSafePath()
        {
            auto tmpDir = std::filesystem::temp_directory_path();
            auto now = std::chrono::steady_clock::now().time_since_epoch().count();
            int pid = GETPID();
            return (tmpDir / std::format("gnuplot_{}_{}.gp", pid,now)).string();
        }
        class GnuplotPipe
        {
            private:
                FILE* Pipe;
                bool PipeOpen=false;
                std::ostringstream Buffer; 
                Output Mode = Output::Persistent;
                bool BufferEmpty = true;

                void writeToPipe(const char * cmd)
                {
                    if (!PipeOpen)
                    {
                        OpenPipe();
                    }
                    fprintf(Pipe, "%s\n", cmd);
                    fflush(Pipe); // forces gnuplot to read the command immediately
                }

                std::filesystem::path ScriptPath;
            public:
                GnuplotPipe(){}

                void OpenPipe()
                {
                    // -persist keeps the window open after the pipe closes
                    std::string cmd;
                    

                    if (Mode == Output::Persistent)
                    {
                        Pipe = popen("gnuplot -persist", "w");
                    }
                    else
                    {
                        //we do this even with scripted mode, just to check that gnuplot exists!
                        Pipe = popen("gnuplot", "w");
                    }
                    if (!Pipe)
                    {
                        throw std::runtime_error("Gnuplot not found!");
                    }


                    PipeOpen = true;

                    if (Mode == Output::Scripted)
                    {
                        Pipe = fopen(ScriptPath.string().c_str(),"w");
                        if (!Pipe)
                        {
                            throw std::runtime_error("Could not open script file '" + ScriptPath.string() + "'");
                        }
                    }

                  
                }
  
                ~GnuplotPipe()
                {
                    Close();
                }

                void SetPersistence(Output level)
                {
                    if (PipeOpen)
                    {
                        Close();
                    }
                    if (level == Output::Scripted && Mode != Output::Scripted)
                    {
                        ScriptPath =makeSafePath();
                        Buffer << "# This gnuplot file was autogenerated by the JSL::Plotting library.\n#\tIt can be invoked by calling \"gnuplot -p " << ScriptPath.string() << "\" on the command line.\n";
                    }
                    Mode = level;   
                }

                void SetScriptPath(std::string path)
                {
                    if (Mode != Output::Scripted)
                    {
                        SetPersistence(Output::Scripted);
                    }
                    ScriptPath = path;
                }
                Output GetMode()
                {
                    return Mode;
                }
                void Close()
                {
                    if (PipeOpen)
                    {
                        send("exit");
                        if (Mode == Output::Scripted)
                        {
                            fclose(Pipe);
                        }
                        else
                        {
                            pclose(Pipe);
                        }
                        PipeOpen = false;
                        Pipe = nullptr;
                    }
                    if (Mode == Output::Scripted)
                    {
                        std::string cmd = "gnuplot -p " + ScriptPath.string() + " &";
                        int ret = system(cmd.c_str());
                        (void)ret; // purely to suppress compiler warnings -- we can't meaningfully check the return value because we've detached the process
                    }
                }

                void send(const std::string& command)
                {
                    flush(); //flush anything in the buffer first
                    writeToPipe(command.c_str());
                }
                void flush()
                {
                    if (!BufferEmpty)
                    {
                        writeToPipe(Buffer.str().c_str());
                        EmptyBuffer();
                    }
                }

                void EmptyBuffer()
                {
                    Buffer.str(std::string());
                    Buffer.clear();
                    BufferEmpty = true;
                }

                template <class T>
                GnuplotPipe & operator<<(T input)
                {
                    Buffer << input;
                    BufferEmpty = false;
                    return *this;
                }
        }; //end pipe class
    } // end internal

} // end plotting