#Auto-generated by the projectmake utility
BUILD_DIR = .build

.PHONY: all test clean resource

# The default target: ensures .build exists, runs cmake, then builds
all:
# 		@make graph
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR)
	@make -C $(BUILD_DIR) --no-print-directory

doc:
	@cd docs && make html

doc-full:
	@cd docs && ./compileDocs

graph:
	@cd docs/visualiser && ./visualise

# Clean up only the build artifacts
purge:
	@rm -rf $(BUILD_DIR)

clean:
	@make purge
	@make all --no-print-directory
