#Auto-generated by the projectmake utility
BUILD_DIR = .build
 
MAKEFLAGS += --no-print-directory
.PHONY: all test clean resource

# The default target: ensures .build exists, runs cmake, then builds
all:
# 		@make graph
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR) -DCMAKE_BUILD_TYPE=Release
	@cmake --build $(BUILD_DIR) --config Release

doc:
	@cd docs && make html

doc-full:
	@cd docs && ./compileDocs

graph:
	@cd docs/visualiser && ./visualise

# Clean up only the build artifacts
purge:
	@rm -rf $(BUILD_DIR)

clean:
	@make purge
	@make all 
