#!/usr/bin/env python3

import sys
import re
import colorbrewer


node_pattern = re.compile(r'node\s+\[fillcolor=\"(.*)\",[\s]+style=filled.*\]\s+"(\S*)"\s*\[label\s*=\s*"(.*)"\]')
edge_pattern = re.compile(r'\"(\S*)\"\s+->\s+\"([^\"]*)\"')


def SanitizeNames(name):
	explode = name.split("/")
	while (explode[0] in ["src","JSL","include"]):
		explode = explode[1:]
	name = "/".join(explode)
	group = "/".join(explode[:-1])
	return name,group

#[pattern,exception]
ignorePattern = [["Log.h",["Display.h","Core.cpp"]]]

def ignoreLink(link,name):

	ignoring = False
	for ignore in ignorePattern:
		if ignore[0] in link:
			ignoring = True
			for exception in ignore[1]:
				if exception in name:
					ignoring = False
	return ignoring
class Network:
	def __init__(self):
		self.Nodes = {}
	def Scan(self,file):
		self.File = file
		try:
			with open(file, 'r') as file:
				for line in file:
					nmatch = node_pattern.search(line)
					if nmatch:
						node = Node(nmatch)
						self.Nodes[node.Name] = node
					else:
						ematch = edge_pattern.search(line)
						if (ematch):
							target,_ = SanitizeNames(ematch.group(1))
							
							if target in self.Nodes.keys():
								self.Nodes[target].Link(ematch.group(2))
							# if 

		except FileNotFoundError:
			print(f"Error: File '{file}' not found.")
		except Exception as e:
			print(f"An error occurred: {e}")

		longest = 0
		for a in self.Nodes:
			if len(a) > longest:
				longest = len(a)	
		self.LongestName = longest
		self.CollateGroups()
		self.TrimSources()
	def Render(self):
		with open(self.File,'w') as file:
			bcol = "#C2C2C4"
			file.write(f"digraph codeviz{{\n\tbgcolor=\"{bcol}\"\n\tconcentrate=true\n\tsplines=true\n\tsep=\"+15,+15\"\n\toverlap=false\n\n\tnode[shape=Mrecord,fontsize=12]\n\n")

			for a in self.Nodes:
				file.write(self.Nodes[a].RenderSelf(self.LongestName))
			for a in self.Nodes:
				file.write(self.Nodes[a].RenderConnections())

			file.write("}")	

	def CollateGroups(self):
		groups = dict()
		for d in self.Nodes:
			group = self.Nodes[d].Group
			if (group not in self.Nodes):
				groups[group] = "#FFFFFF"
		
		#check for for folder-level matches
		for d in self.Nodes:
			self.Nodes[d].CheckFolder(groups)

		palette = colorbrewer.Set3

		colmax = max(palette.keys())	

		N = max(min(palette.keys()),min(max(palette.keys()),len(groups)))
		print(f"Rendering using {N} colours")
		if N < len(groups):
			print("\tThis exceeds the number of colours in the colorbrewer syntax. Duplications may occur")
		for i,g in enumerate(groups):
			rgb = palette[N][i%N]
			palefac = 0.5
			pale = tuple([int(x + (255-x)*palefac) for x in rgb])
			darkfac = 0.8
			dark = tuple([int(x *darkfac) for x in rgb])
			headerhex = ('#%02x%02x%02x' % rgb)
			sourcehex = ('#%02x%02x%02x' % pale)
			darkhex = ('#%02x%02x%02x' % dark)

			groups[g] = [headerhex,sourcehex,darkhex]

		for d in self.Nodes:
			self.Nodes[d].SetColour(groups[self.Nodes[d].Group])

	def TrimSources(self):
		for node in self.Nodes.values():
			if not node.IsHeader:
				validLinks = 0
				for link in node.Links:
					if not ignoreLink(link[0],node.Name):
						validLinks += 1
				if validLinks < 2:
					node.Style = "invis"
					header = str(node.Name).removesuffix(".cpp") + ".h"
					if header in self.Nodes:
						self.Nodes[header].Label +="\\nand .cpp"
class Node:
	def __init__(self,match):
		self.Colour = match.group(1)
		self.Name,self.Group = SanitizeNames(match.group(2))
		self.Label = self.Name
		self.Style = "\"rounded,filled\""
		self.Shape = "box"
		self.IsHeader= True if ".h" in self.Name else False
		self.Links = []
		self.Outline = "black"
		self.IsJunction = False
	def Link(self,target):
		n,g = SanitizeNames(target)
		self.Links.append([n,g])

	def RenderSelf(self,longest):
		self._buffer = ' '*(longest + 1-len(self.Name))
		
		return f"\tnode [fillcolor=\"{self.Colour}\", style={self.Style}, shape={self.Shape},color=\"{self.Outline}\"] \"{self.Name}\"{self._buffer}[label=\"{self.Label}\"]\n"
	def RenderConnections(self):
		s = ""
		if self.Style == "invis":
			return ""
		
		for link,group in self.Links:
			if ignoreLink(link,self.Name):
				continue
			if group == self.Group:
				s += f"\t\"{self.Name}\"{self._buffer}-> \"{link}\"[weight=10,penwidth=2]\n"
			else:
				s += f"\t\"{self.Name}\"{self._buffer}-> \"{link}\"[style=dashed,penwidth=3,color=\"{self.Line}\"]\n"
			
		return s
		
	def CheckFolder(self,groups):
		strip = self.Name.removesuffix(".h")
		if strip in groups:
			self.Group = strip
			self.Shape="folder"
		if self.Group == '':
			self.Shape = "tripleoctagon"
			self.Label = "Library Entry"
	def SetColour(self,col):
		if ".cpp" in self.Name:
			self.Colour = col[1]
			self.Outline = col[1]
			self.Line = col[2]
			# self.Shape = "diamond"
		else:
			self.Colour = col[0]
			self.Outline = "#000000"
			self.Line = col[2]
if __name__ == "__main__":
	if len(sys.argv) != 2:
		print(f"Usage: {sys.argv[0]} <filename>")
	else:
		N = Network()
		N.Scan(sys.argv[1])
		N.Render()